// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AccessPointSpec defines the desired state of AccessPoint.
type AccessPointSpec struct {

	// The ID or Amazon Resource Name (ARN) of the S3 File System.
	//
	// Regex Pattern: `^(arn:aws[-a-z]*:s3files:[0-9a-z-:]+:file-system/fs-[0-9a-f]{17,40}|fs-[0-9a-f]{17,40})$`
	FileSystemID  *string                                  `json:"fileSystemID,omitempty"`
	FileSystemRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"fileSystemRef,omitempty"`
	// The POSIX identity with uid, gid, and secondary group IDs for user enforcement
	// when accessing the file system through this access point.
	PosixUser *PosixUser `json:"posixUser,omitempty"`
	// The root directory path for the access point, with optional creation permissions
	// for newly created directories.
	RootDirectory *RootDirectory `json:"rootDirectory,omitempty"`
	// An array of key-value pairs to apply to the access point for resource tagging.
	Tags []*Tag `json:"tags,omitempty"`
}

// AccessPointStatus defines the observed state of AccessPoint
type AccessPointStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The ID of the access point.
	//
	// Regex Pattern: `^(arn:aws[-a-z]*:s3files:[0-9a-z-:]+:file-system/fs-[0-9a-f]{17,40}/access-point/fsap-[0-9a-f]{17,40}|fsap-[0-9a-f]{17,40})$`
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty"`
	// The name of the access point.
	//
	// Regex Pattern: `^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$`
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty"`
	// The Amazon Web Services account ID of the access point owner.
	//
	// Regex Pattern: `^(\d{12})|(\d{4}-{4}-\d{4})$`
	// +kubebuilder:validation:Optional
	OwnerID *string `json:"ownerID,omitempty"`
	// The current status of the access point.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
}

// AccessPoint is the Schema for the AccessPoints API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="ID",type=string,priority=0,JSONPath=`.status.id`
// +kubebuilder:printcolumn:name="FILESYSTEMID",type=string,priority=0,JSONPath=`.spec.fileSystemID`
// +kubebuilder:printcolumn:name="STATUS",type=string,priority=0,JSONPath=`.status.status`
// +kubebuilder:printcolumn:name="Synced",type="string",priority=0,JSONPath=".status.conditions[?(@.type==\"ACK.ResourceSynced\")].status"
type AccessPoint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AccessPointSpec   `json:"spec,omitempty"`
	Status            AccessPointStatus `json:"status,omitempty"`
}

// AccessPointList contains a list of AccessPoint
// +kubebuilder:object:root=true
type AccessPointList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccessPoint `json:"items"`
}

func init() {
	SchemeBuilder.Register(&AccessPoint{}, &AccessPointList{})
}
