// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MountTargetSpec defines the desired state of MountTarget.
type MountTargetSpec struct {

	// The ID or Amazon Resource Name (ARN) of the S3 File System to create the
	// mount target for.
	//
	// Regex Pattern: `^(arn:aws[-a-z]*:s3files:[0-9a-z-:]+:file-system/fs-[0-9a-f]{17,40}|fs-[0-9a-f]{17,40})$`
	FileSystemID  *string                                  `json:"fileSystemID,omitempty"`
	FileSystemRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"fileSystemRef,omitempty"`
	// The IP address type for the mount target. If not specified, IPV4_ONLY is
	// used. The IP address type must match the IP configuration of the specified
	// subnet.
	IPAddressType *string `json:"ipAddressType,omitempty"`
	// A specific IPv4 address to assign to the mount target. If not specified and
	// the IP address type supports IPv4, an address is automatically assigned from
	// the subnet's available IPv4 address range. The address must be within the
	// subnet's CIDR block and not already in use.
	//
	// Regex Pattern: `^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$`
	IPv4Address *string `json:"ipv4Address,omitempty"`
	// A specific IPv6 address to assign to the mount target. If not specified and
	// the IP address type supports IPv6, an address is automatically assigned from
	// the subnet's available IPv6 address range. The address must be within the
	// subnet's IPv6 CIDR block and not already in use.
	IPv6Address       *string                                    `json:"ipv6Address,omitempty"`
	SecurityGroupRefs []*ackv1alpha1.AWSResourceReferenceWrapper `json:"securityGroupRefs,omitempty"`
	// An array of VPC security group IDs to associate with the mount target's network
	// interface. These security groups control network access to the mount target.
	// If not specified, the default security group for the subnet's VPC is used.
	// All security groups must belong to the same VPC as the subnet.
	SecurityGroups []*string `json:"securityGroups,omitempty"`
	// The ID of the subnet where the mount target will be created. The subnet must
	// be in the same Amazon Web Services Region as the file system. For file systems
	// with regional availability, you can create mount targets in any subnet within
	// the Region. The subnet determines the Availability Zone where the mount target
	// will be located.
	//
	// Regex Pattern: `^subnet-[0-9a-f]{8,40}$`
	SubnetID  *string                                  `json:"subnetID,omitempty"`
	SubnetRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"subnetRef,omitempty"`
}

// MountTargetStatus defines the observed state of MountTarget
type MountTargetStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The unique and consistent identifier of the Availability Zone where the mount
	// target is located. For example, use1-az1 is an Availability Zone ID for the
	// us-east-1 Amazon Web Services Region, and it has the same location in every
	// Amazon Web Services account.
	// +kubebuilder:validation:Optional
	AvailabilityZoneID *string `json:"availabilityZoneID,omitempty"`
	// The ID of the mount target, assigned by S3 Files. This ID is used to reference
	// the mount target in subsequent API calls.
	//
	// Regex Pattern: `^fsmt-[0-9a-f]{17,40}$`
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty"`
	// The ID of the network interface that S3 Files created when it created the
	// mount target. This network interface is managed by the service.
	// +kubebuilder:validation:Optional
	NetworkInterfaceID *string `json:"networkInterfaceID,omitempty"`
	// The Amazon Web Services account ID of the mount target owner.
	//
	// Regex Pattern: `^(\d{12})|(\d{4}-{4}-\d{4})$`
	// +kubebuilder:validation:Optional
	OwnerID *string `json:"ownerID,omitempty"`
	// The lifecycle state of the mount target. Valid values are: AVAILABLE (the
	// mount target is available for use), CREATING (the mount target is being created),
	// DELETING (the mount target is being deleted), DELETED (the mount target has
	// been deleted), or ERROR (the mount target is in an error state), or UPDATING
	// (the mount target is being updated).
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
	// Additional information about the mount target status. This field provides
	// more details when the status is ERROR, or during state transitions.
	// +kubebuilder:validation:Optional
	StatusMessage *string `json:"statusMessage,omitempty"`
	// The ID of the VPC where the mount target is located.
	// +kubebuilder:validation:Optional
	VPCID *string `json:"vpcID,omitempty"`
}

// MountTarget is the Schema for the MountTargets API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="ID",type=string,priority=0,JSONPath=`.status.id`
// +kubebuilder:printcolumn:name="STATUS",type=string,priority=0,JSONPath=`.status.status`
// +kubebuilder:printcolumn:name="Synced",type="string",priority=0,JSONPath=".status.conditions[?(@.type==\"ACK.ResourceSynced\")].status"
type MountTarget struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              MountTargetSpec   `json:"spec,omitempty"`
	Status            MountTargetStatus `json:"status,omitempty"`
}

// MountTargetList contains a list of MountTarget
// +kubebuilder:object:root=true
type MountTargetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MountTarget `json:"items"`
}

func init() {
	SchemeBuilder.Register(&MountTarget{}, &MountTargetList{})
}
