// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	"github.com/aws/aws-sdk-go/aws"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = ackv1alpha1.AWSAccountID("")
)

// Specifies the permissions to set on newly created directories within the
// file system.
type CreationPermissions struct {
	OwnerGID    *int64  `json:"ownerGID,omitempty"`
	OwnerUID    *int64  `json:"ownerUID,omitempty"`
	Permissions *string `json:"permissions,omitempty"`
}

// Specifies a rule that controls when cached data expires from the file system
// based on last access time.
type ExpirationDataRule struct {
	DaysAfterLastAccess *int64 `json:"daysAfterLastAccess,omitempty"`
}

// Specifies a rule that controls how data is imported from S3 into the file
// system.
type ImportDataRule struct {
	Prefix       *string `json:"prefix,omitempty"`
	SizeLessThan *int64  `json:"sizeLessThan,omitempty"`
	Trigger      *string `json:"trigger,omitempty"`
}

// Contains information about an S3 File System Access Point returned in list
// operations.
type ListAccessPointsDescription struct {
	AccessPointARN *string `json:"accessPointARN,omitempty"`
	AccessPointID  *string `json:"accessPointID,omitempty"`
	FileSystemID   *string `json:"fileSystemID,omitempty"`
	Name           *string `json:"name,omitempty"`
	OwnerID        *string `json:"ownerID,omitempty"`
	// Specifies the POSIX identity with uid, gid, and secondary group IDs for user
	// enforcement.
	PosixUser *PosixUser `json:"posixUser,omitempty"`
	// Specifies the root directory path and optional creation permissions for newly
	// created directories.
	RootDirectory *RootDirectory `json:"rootDirectory,omitempty"`
	Status        *string        `json:"status,omitempty"`
}

// Contains information about an S3 File System returned in list operations.
type ListFileSystemsDescription struct {
	Bucket        *string      `json:"bucket,omitempty"`
	CreationTime  *metav1.Time `json:"creationTime,omitempty"`
	FileSystemARN *string      `json:"fileSystemARN,omitempty"`
	FileSystemID  *string      `json:"fileSystemID,omitempty"`
	Name          *string      `json:"name,omitempty"`
	OwnerID       *string      `json:"ownerID,omitempty"`
	RoleARN       *string      `json:"roleARN,omitempty"`
	Status        *string      `json:"status,omitempty"`
	StatusMessage *string      `json:"statusMessage,omitempty"`
}

// Contains information about a mount target returned in list operations.
type ListMountTargetsDescription struct {
	AvailabilityZoneID *string `json:"availabilityZoneID,omitempty"`
	FileSystemID       *string `json:"fileSystemID,omitempty"`
	IPv4Address        *string `json:"ipv4Address,omitempty"`
	IPv6Address        *string `json:"ipv6Address,omitempty"`
	MountTargetID      *string `json:"mountTargetID,omitempty"`
	NetworkInterfaceID *string `json:"networkInterfaceID,omitempty"`
	OwnerID            *string `json:"ownerID,omitempty"`
	Status             *string `json:"status,omitempty"`
	StatusMessage      *string `json:"statusMessage,omitempty"`
	SubnetID           *string `json:"subnetID,omitempty"`
	VPCID              *string `json:"vpcID,omitempty"`
}

// Specifies the POSIX identity with uid, gid, and secondary group IDs for user
// enforcement.
type PosixUser struct {
	GID           *int64   `json:"gid,omitempty"`
	SecondaryGIDs []*int64 `json:"secondaryGIDs,omitempty"`
	UID           *int64   `json:"uid,omitempty"`
}

// Specifies the root directory path and optional creation permissions for newly
// created directories.
type RootDirectory struct {
	// Specifies the permissions to set on newly created directories within the
	// file system.
	CreationPermissions *CreationPermissions `json:"creationPermissions,omitempty"`
	Path                *string              `json:"path,omitempty"`
}

// A key-value pair for resource tagging.
type Tag struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}
